### ISSUE TITLE
thought Sansco would be supported

### ISSUE THREAD

**Issue by atv2016** [rroller/dahua#121]
## Version of the custom_component
 latest

## Configuration

```yaml

Add your logs here.
This error originated from a custom integration.

Logger: custom_components.dahua
Source: custom_components/dahua/config_flow.py:198 
Integration: Dahua (documentation, issues) 
First occurred: 14:52:55 (12 occurrences) 
Last logged: 19:00:44

Could not connect to Dahua device via the RPC2 API, falling back to cgi

```

## Describe the bug

Can't seem to connect to my NVR, even though RTSP string works fine on my browser or VLC or in webrtc even.

## Debug log

```text

Add your logs here.

```
