### ISSUE TITLE
Is snapshot making proper jpg with mimetype?

### ISSUE THREAD

**Issue by pszafer** [rroller/dahua#200]
## Version of the custom_component

Version 0.9.40

## Configuration

```yaml

Error sending photo: Image_process_failed. Args: (), kwargs: {'chat_id': 839230461, 'photo': <_io.BufferedReader name='/config/www/tmp/sn_front.jpg'>, 'caption': 'Auto', 'disable_notification': False, 'reply_markup': None, 'timeout': None, 'parse_mode': 'Markdown'}


```

## Describe the bug

Hello, first, thanks for this integration!
I want to send picture via telegram bot when somebody is detected.

I used automation like this:
```yaml
 - service: camera.snapshot
    data:
      filename: /config/www/tmp/sn_front.jpeg
    target:
      entity_id: camera.front_sub_2
  - service: notify.tgw
    data:
      data:
        photo:
          file: /config/www/tmp/sn_front.jpeg
          caption: Auto
      message: Samochod front
```

it end up with log as above.
Looking through other issues it seems that snapshot service is making jpg without proper mimetype.
https://github.com/home-assistant/core/issues/7413

Can you check it out? Thanks!
