### ISSUE TITLE
Home Kit motion sensor

### ISSUE THREAD

**Issue by stefanoferrario** [rroller/dahua#217]
Hi,

I add some NVR Dahua camera's to Home Assistant and I can see all cameras in Home Kit app. 
Unfortunately I noticed that motion sensor in Home Kit app always not detect motion.
Is there a specific configuration?

Thanks

**Comment by zios0007** [comment]
This is a HomeKit Bridge configuration question rather than an integration one, and it has a specific answer.

Home Assistant's HomeKit Bridge does not attach a motion sensor to a camera on its own. A camera accessory reports motion only when you say which entity to use, with `linked_motion_sensor`:

```yaml
homekit:
  - filter:
      include_entities:
        - camera.front_door
        - binary_sensor.front_door_motion
    entity_config:
      camera.front_door:
        linked_motion_sensor: binary_sensor.front_door_motion
```

Without that line the camera shows up in the Home app with no motion at all, which is what you are seeing.

The binary sensors this integration creates already carry the motion device class, so they work as the linked entity with no changes needed here.

@rroller closeable, there is nothing to change in the integration.
