### ISSUE TITLE
'set_text_overlay' service does not allow Jinja2 templates / sensor values

### ISSUE THREAD

**Issue by jrb80** [rroller/dahua#274]
`dahua.set_text_overlay` service does not allow Jinja2 templates. For example;

```
tap_action:
  action: call-service
  service: dahua.set_custom_overlay
  target:
    entity_id:
      - camera.street_main
  data:
    group: 0
    text1: Cars {{ states('sensor.smart_motion_vehicle') }}
    text2: People {{ states('sensor.smart_motion_human') }}
```
When the automation/script is committed it nulls the template - example below

```
tap_action:
  action: call-service
  service: dahua.set_custom_overlay
  target:
    entity_id:
      - camera.street_main
  data:
    group: 0
    text1:  '[object Object]': null
    text2:  '[object Object]': null
name: Custom Overlay
```
The above Jinja2 template works correctly in the developer tools.

`dahua.set_text_overlay` service should be able to consume sensor data / templates for it to be useful. Using a static text string works but as mentioned, not very useful.
