### ISSUE TITLE
no SMD or IVS human/vehicle detections

### ISSUE THREAD

**Issue by n0way0ut** [rroller/dahua#288]
hello,

I installed the integraion on HA and tried to check the events received with dahua_event_received, but I see only CrossRegionDetection events, nothing about vehicle or human, they are enabled because with the dahua application DMSS I receive the alerts.
What may I check?
thanks

**Comment by n0way0ut** [comment]
ok, I get these:

```
event_type: dahua_event_received
data:
  Code: CrossRegionDetection
  action: Start
  index: "5"
  data:
    Action: Appear
    Class: Normal
    CountInGroup: 1
    DetectRegion:
      - - 55
        - 97
      - - 8082
        - 97
      - - 8136
        - 8191
      - - 0
    - 8118
      - - 55
        - 97
    EventID: 15171
    GroupID: 5170
    LocaleTime: "2023-06-26 21:22:01"
    Name: Regola2
    Object:
      Action: Appear
      BelongID: 0
      BoundingBox:
        - 2888
        - 4320
        - 3224
        - 5632
      Center:
        - 3056
        - 4976
      Confidence: 0
      LowerBodyColor:
        - 0
        - 0
        - 0
        - 0
      MainColor:
        - 0
        - 0
        - 0
        - 0
      ObjectID: 77171
      ObjectType: Human
      RelativeID: 0
      Speed: 0
    PTS: 43842500450
    RuleID: 4
    Track: []
    UTC: 1687814520
    UTCMS: 945
  name: Garage
  DeviceName: Garage
origin: LOCAL
time_fired: "2023-06-26T20:22:00.362846+00:00"
context:
  id: XXXXXXXXXXX
  parent_id: null
  user_id: null
```

and 


```
event_type: dahua_event_received
data:
  Code: CrossRegionDetection
  action: Start
  index: "3"
  data:
    Action: Appear
    Class: Normal
    CountInGroup: 1
    DetectRegion:
      - - 18
        - 73
      - - 8155
        - 49
      - - 8155
        - 8167
      - - 18
        - 8142
      - - 55
        - 73
    EventID: 13003
    GroupID: 3002
    LocaleTime: "2023-06-26 21:22:00"
    Name: Regola2
    Object:
      Action: Appear
      Attachment: []
      BelongID: 0
      BoundingBox:
        - 3824
        - 808
        - 4704
        - 2456
      BrandYear: 0
      CarLogoIndex: 0
      CarWindow:
        BoundingBox:
          - 0
          - 0
          - 0
          - 0
      Category: Unknown
      CategoryConfidence: 0
      Center:
        - 4264
        - 1632
      Confidence: 0
      FusionInfo:
        BelongID: 0
        CartPosX: 0
        CartPosY: 0
        GpsPosValid: 0
        Latitude: 0
          Longitude: 0
        ObjectSource: 0
        RadarCoorXyValid: 0
        Speed: 0
        SpeedValid: 0
        SpeedX: 0
        SpeedY: 0
      MainColor:
        - 0
        - 0
        - 0
        - 0
      ObjectID: 4290
      ObjectType: Vehicle
      PTZ:
        - 0
        - 0
        - 0
      RelativeID: 0
      Speed: 0
      SubBrand: 0
      Text: Unknown
      VehiclePosture: 1
      VehicleSignConfidence: 0
      carLenMode: 0
      carLength: 0
      carTripLineDirection: 0
    PTS: 44324508100
    RealUTC: 1687810919
    RuleID: 10
    Track: []
    UTC: 1687814519
    UTCMS: 631
  name: Gabry
  DeviceName: Gabry
origin: LOCAL
time_fired: "2023-06-26T20:22:00.296878+00:00"
context:
  id: XXXXXXX
  parent_id: null
  user_id: null
```

as you can see there is the ObjectType that differentiate vehicle and human, but this is esposed in the same binary_sensor on HA, is there a way to have separate sensor for human and vehicle?

**Comment by jgverweij** [comment]
> ok, I get these:
> 
> as you can see there is the ObjectType that differentiate vehicle and human, but this is esposed in the same binary_sensor on HA, is there a way to have separate sensor for human and vehicle?

You can make use of event triggers in an automation, or set up trigger-based sensors yourself:
```yaml

trigger:
  - platform: event
    event_type: dahua_event_received
    event_data:
      name: Dahua
      Code: CrossLineDetection
      action: Start
    id: general
  - platform: event
    event_type: dahua_event_received
    event_data:
      name: Dahua
      Code: CrossLineDetection
      action: Start
      data:
        Object:
          ObjectType: Human
    id: Human Motion
  - platform: event
    event_type: dahua_event_received
    event_data:
      name: Dahua
      Code: CrossLineDetection
      action: Start
      data:
        Object:
          ObjectType: Vehicle
    id: Vehicle Motion
```

**Comment by ns-gcutolo** [comment]
interesting, but how to build a sensor that updates on each detection?

**Comment by zios0007** [comment]
Two separate things here, and the first one is not a fault.

**Why you only see `CrossRegionDetection`.** That is what the camera sends. Dahua's SMD and IVS are different subsystems, and plenty of cameras, Amcrest doorbells included, issue IVS `CrossRegionDetection` for what the app calls human detection. @GaryOkie set this out in #243. DMSS showing you "human" is DMSS reading `ObjectType` out of that same event, not a different event.

**@verjager's question is the real feature ask**, and it is a good one. Your own payload has it:

```
Code: CrossRegionDetection
data:
  Object:
    ObjectType: Human
```

so the distinction is on the wire and the integration collapses it into one binary sensor. Splitting `ObjectType` into separate human and vehicle sensors is a genuine improvement rather than a workaround.

Until then it is available from the event bus, keyed on the same field:

```yaml
trigger:
  - platform: event
    event_type: dahua_event_received
condition:
  - "{{ trigger.event.data.Code == 'CrossRegionDetection' }}"
  - "{{ trigger.event.data.data.Object.ObjectType == 'Human' }}"
```

Leaving open for the split, which is worth doing.

**Comment by zios0007** [comment]
**Correcting myself.** I said above that these cameras do not emit `SmartMotionHuman`, so you should subscribe to `CrossRegionDetection` instead. The first half is true about the wire. The conclusion was wrong, and following it gives you a worse sensor, because `CrossRegionDetection` fires for vehicles and anything else that trips the rule.

The integration already translates. Since 0.5.0, in August 2021, `translate_event_code` reads the object type out of a CrossLine or CrossRegion event and fires the matching smart-motion code as well:

```python
object_type = data.get("Object", {}).get("ObjectType", "").lower()
...
if object_type == "human":
    codes.append("SmartMotionHuman")
elif object_type == "vehicle":
    codes.append("SmartMotionVehicle")
```

@n0way0ut's payload on #288 is exactly the shape that reads:

```
Code: CrossRegionDetection
data:
  Object:
    ObjectType: Human
```

So on a camera sending that, **`SmartMotionHuman` is the sensor to use**, and it fires only for people. Both sensors fire when both are subscribed, which is the intended behaviour: the Cross Region one for "the rule tripped", the smart-motion one for "it was a person".

**The thing that actually stops it working is subscription.** The sensors that exist come from the event list stored on the entry, and an entry keeps whatever list it was created with. If `SmartMotionHuman` was not ticked when the camera was added, no amount of the camera sending it will produce a sensor. Fix it in **Integration, Configure**, not by removing and re-adding the device.

If `SmartMotionHuman` **is** subscribed, the sensor exists, and it still never turns on, then this is a real bug rather than a configuration problem, and it is worth its own investigation. The useful evidence is a debug log covering one detection, showing what arrived and what the translation made of it. That is the case @Bubbgump209 reported on #276, where the camera sends `SmartMotionHuman` natively, confirmed with curl, and the sensor still does nothing. I do not yet have an explanation for that one.

Apologies for the detour. I should have read the translation before advising a workaround around it.
