### ISSUE TITLE
AV-VTA05-22AV2 - Get Button Press

### ISSUE THREAD

**Issue by Marcwa19197** [rroller/dahua#329]
Hello,

thanks for the integration!
Im using a AV-VTA05-22AV2 with 2 Bell-Buttons. (2-family House).

How can i get the press of one of the buttons to trigger an automation in Home-Assistant?

Thank you very much.

**Comment by mooton85** [comment]
In developer tools go to events and subscribe to dahua_event_received, the press the button and see if an event comes through specific to those buttons

**Comment by Marcwa19197** [comment]
I can see those events:

`event_type: dahua_event_received
data:
  Code: InterVideoAccess
  action: Pulse
  index: "0"
  data:
    Type: WebAllLogout
  name: sprechanlage
  DeviceName: sprechanlage
origin: LOCAL
time_fired: "2024-01-04T16:09:51.269515+00:00"
context:
  id: 01HKAKSXD5YAPQEBJQW8M82XT5
  parent_id: null
  user_id: null
  
  event_type: dahua_event_received
data:
  Code: InterVideoAccess
  action: Pulse
  index: "0"
  data:
    Type: WebAllLogout
  name: sprechanlage
  DeviceName: sprechanlage
origin: LOCAL
time_fired: "2024-01-04T16:09:21.272477+00:00"
context:
  id: 01HKAKS03RZTDG1JYASE356MK0
  parent_id: null
  user_id: null


event_type: dahua_event_received
data:
  Code: InterVideoAccess
  action: Pulse
  index: "0"
  data:
    Type: WebAllLogout
  name: sprechanlage
  DeviceName: sprechanlage
origin: LOCAL
time_fired: "2024-01-04T16:09:13.999935+00:00"
context:
  id: 01HKAKRS0FAY5DT61696DASQDE
  parent_id: null
  user_id: null
  
  
  event_type: dahua_event_received
data:
  Code: VideoMotion
  action: Stop
  index: "0"
  name: sprechanlage
  DeviceName: sprechanlage
origin: LOCAL
time_fired: "2024-01-04T16:08:27.929443+00:00"
context:
  id: 01HKAKQC0SXP7ASFN5WBTPH3WZ
  parent_id: null
  user_id: null
  
  
  event_type: dahua_event_received
data:
  Code: VideoMotion
  action: Start
  index: "0"
  name: sprechanlage
  DeviceName: sprechanlage
origin: LOCAL
time_fired: "2024-01-04T16:08:02.037914+00:00"
context:
  id: 01HKAKPJQNE1DJZMEWZKFY4VF3
  parent_id: null
  user_id: null
  
  
  event_type: dahua_event_received
data:
  Code: VideoMotion
  action: Stop
  index: "0"
  name: sprechanlage
  DeviceName: sprechanlage
origin: LOCAL
time_fired: "2024-01-04T16:07:46.938922+00:00"
context:
  id: 01HKAKP3ZTPW8FNZ60Q1WRA7AP
  parent_id: null
  user_id: null


event_type: dahua_event_received
data:
  Code: VideoMotion
  action: Start
  index: "0"
  name: sprechanlage
  DeviceName: sprechanlage
origin: LOCAL
time_fired: "2024-01-04T16:07:37.029873+00:00"
context:
  id: 01HKAKNTA5C0PYQ0SAZA5YM0YB
  parent_id: null
  user_id: null
`

I assume Index = 0 first button, index 1 = second button?

**Comment by Marcwa19197** [comment]
i tested with:

```
event_type: dahua_event_received
data:
  Code: InterVideoAccess
  action: Pulse
  index: "0"
  data:
    Type: WebAllLogout
  name: sprechanlage
  DeviceName: sprechanlage
origin: LOCAL
time_fired: "2024-01-04T16:09:51.269515+00:00"
context:
  id: 01HKAKSXD5YAPQEBJQW8M82XT5
  parent_id: null
  user_id: null
```
  
and with

```
event_type: dahua_event_received
data:
  Code: VideoMotion
  action: Start
  index: "0"
  name: sprechanlage
  DeviceName: sprechanlage
origin: LOCAL
time_fired: "2024-01-04T16:07:37.029873+00:00"
context:
  id: 01HKAKNTA5C0PYQ0SAZA5YM0YB
  parent_id: null
  user_id: null
```


But with no success - sometimes these events are fired even without pressing the doorbell-button... :-/ someone an idea?
