### ISSUE TITLE
"enable_recording and "disable_recording function

### ISSUE THREAD

**Issue by JLFN** [rroller/dahua#33]
Hi
Very nice project !
I have been using for my Dahua cameras,  amcrest  intregration for a while but its very bad now, is it possible to implement
enable recording and disable recordning
Thank you in advance.

See link

https://github.com/home-assistant/core/blob/5c5e43afc127fe420f314c01ee2e78d347631adc/homeassistant/components/amcrest/camera.py#L39

i use it like this
```yaml
  - alias: Camera Record on
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: alarm_control_panel.ha_alarm
        to: 'armed_away'
      - platform: state
        entity_id: alarm_control_panel.ha_alarm
        to: 'armed_home'
    action:
      - service: amcrest.enable_motion_recording
        data:
         entity_id:
          - camera.carport
          - camera.laundry
          - camera.kitchen
          - camera.living_room
          - camera.family_room
#
  - alias: Camera Record off
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: alarm_control_panel.ha_alarm
        to: 'disarmed'
    action:
      - service: amcrest.disable_motion_recording
        data:
         entity_id:
          - camera.carport
          - camera.laundry
          - camera.kitchen
          - camera.living_room
          - camera.family_room
```

**Comment by rroller** [comment]
Ack. I'll implement this as soon as I can get to it. Thanks for the great idea!

**Comment by rroller** [comment]
One clarification. Does this enable recording, like 24/7 recording? Or only enable recording on motion? 

If it's only for motion this is already supported with the existing switch, see this image...

<img width="367" alt="Screen Shot 2021-06-29 at 10 18 18 PM" src="https://user-images.githubusercontent.com/445655/123905828-eb537800-d927-11eb-8f48-ff0598e89d85.png">

You can also use the service `camera.enable_motion_detection` and `camera.disable_motion_detection`

<img width="1225" alt="Screen Shot 2021-06-29 at 10 19 54 PM" src="https://user-images.githubusercontent.com/445655/123905937-248be800-d928-11eb-9104-1b049facdc34.png">

If that's not what you are looking for then I'll be happy to build in support for what you need.

**Comment by JLFN** [comment]
> One clarification. Does this enable recording, like 24/7 recording? Or only enable recording on motion?
> 
> If it's only for motion this is already supported with the existing switch, see this image...
> 
> <img alt="Screen Shot 2021-06-29 at 10 18 18 PM" width="367" src="https://user-images.githubusercontent.com/445655/123905828-eb537800-d927-11eb-8f48-ff0598e89d85.png">
> 
> You can also use the service `camera.enable_motion_detection` and `camera.disable_motion_detection`
> 
> <img alt="Screen Shot 2021-06-29 at 10 19 54 PM" width="1225" src="https://user-images.githubusercontent.com/445655/123905937-248be800-d928-11eb-9104-1b049facdc34.png">
> 
> If that's not what you are looking for then I'll be happy to build in support for what you need.

This enable recordning when there is motion.

**Comment by rroller** [comment]
How do you do this in the camera's UI? Are you using "Record Mode"?

![image](https://user-images.githubusercontent.com/445655/124206758-d21e0900-da98-11eb-94f9-59251f65944e.png)

**Comment by rroller** [comment]
I've added a new service: `dahua.set_record_mode`. It takes a `mode`, which can be:
* `On` is always on recording
* `Off` is always off
* `Auto` based on motion settings

You can find it in the service explorer:

![image](https://user-images.githubusercontent.com/445655/124219264-dd7d2e80-dab0-11eb-973a-62f8ebdec497.png)


YAML would look something like this...
```yaml
service: dahua.set_record_mode
target:
  entity_id: camera.server_cam_main
data:
  mode: 'On'
```
