### ISSUE TITLE
What’s the best way to display camera on dashboard?

### ISSUE THREAD

**Issue by deadrubberboy** [rroller/dahua#382]
Hello! When I add the stream entity it’s just an icon not the actual stream or thumbnail.  Is this possible? Would like similar functionality as HomeKit dashboard.

**Comment by deadrubberboy** [comment]
Hello?

**Comment by jgverweij** [comment]
You can use an picture-entity card:

```yaml
type: picture-entity
entity: camera.dahua_sub_2
camera_view: live
show_state: false
show_name: false
```

For low latency you could also try:
https://github.com/AlexxIT/WebRTC

This requires more configuration

**Comment by deadrubberboy** [comment]
Thank you!

**Comment by zios0007** [comment]
@verjager's answer is right and worth keeping visible, since this is asked often.

A camera entity is not a card. Add a picture card pointed at it:

```yaml
type: picture-entity
entity: camera.your_camera_sub
camera_view: live
show_state: false
show_name: false
```

`camera_view: live` gives a stream; leaving it out gives a still that refreshes, which is lighter and often the better choice on a dashboard with several cameras.

Two things worth knowing, because they are the usual next problem:

- point it at the **sub** stream rather than the main one. Sub streams are far lighter and start faster
- if the stream will not play at all, check the codec. Home Assistant handles H.264 reliably and frequently fails to start H.265. That is now in the README's Known Issues

@rroller closeable, answered.
