### ISSUE TITLE
IPC-T54IR-ZE s3 Zoom ability?

### ISSUE THREAD

**Issue by Archy54** [rroller/dahua#386]
Can IPC-T54IR-ZE s3 do zoom in HA? I couldn't see a sensor for zoom.

**Comment by zios0007** [comment]
Yes, and it is a service rather than a sensor, which is why you could not find it.

`dahua.ptz_move` takes `zoom_in` and `zoom_out` as directions:

```yaml
action: dahua.ptz_move
target:
  entity_id: camera.your_camera
data:
  direction: zoom_in
  speed: 5
```

It moves while the command runs and stops afterwards, so the duration is how far it travels.

There is also `dahua.set_focus_zoom`, which sets an absolute focus and zoom rather than moving by a step, if you want to return to a known position.

Worth knowing that a zoom entity does not exist because Home Assistant has no zoom entity type. Cameras expose actions, so zoom is an action.

@rroller closeable.
