### ISSUE TITLE
Add doorbell to HomeKit

### ISSUE THREAD

**Issue by igorakintev** [rroller/dahua#388]
Hi.
Is it possible to add Dahua doorbell to HomeKit to answer a call and open a door.

Thanks in advance.

**Comment by zios0007** [comment]
Yes, and it is configured on the HomeKit side rather than here.

Home Assistant's HomeKit Bridge supports a video doorbell, and it needs to be told which entity is the bell and which is the motion sensor, because it cannot infer either:

```yaml
homekit:
  - filter:
      include_entities:
        - camera.doorbell
        - binary_sensor.doorbell_button_pressed
    entity_config:
      camera.doorbell:
        linked_doorbell_sensor: binary_sensor.doorbell_button_pressed
        linked_motion_sensor: binary_sensor.doorbell_motion
```

With `linked_doorbell_sensor` set, a press produces a HomeKit doorbell notification with a snapshot.

**Answering the call is not possible.** HomeKit two-way audio needs the doorbell to speak HomeKit's protocol, and the audio path here is RTSP through Home Assistant. Talking back is not something the bridge can offer for a generic camera.

**Opening the door works** as an ordinary switch or button exposed to HomeKit: this integration provides an Open Door button on VTOs, and that can be included in the HomeKit filter like any other entity.

So: doorbell notification yes, door open yes, two-way audio no.
