### ISSUE TITLE
Disable/enable an IVS Rule

### ISSUE THREAD

**Issue by stefanoferrario** [rroller/dahua#433]
I tried to send an action to disable or enable an IVS rule, but it doesn't seem to be working.

<img width="1205" alt="Screenshot 2024-12-04 alle 15 38 04" src="https://github.com/user-attachments/assets/9b40f174-5b67-46cb-a707-1bf83dbd7864">

```
action: dahua.enable_ivs_rule
data:
  index: 1
  enabled: false
target:
  entity_id: camera.telecamera_est_1_main
```

This is the error:
<img width="1258" alt="Screenshot 2024-12-04 alle 15 42 53" src="https://github.com/user-attachments/assets/4b3dd465-626b-4d1f-8601-164f2ab4eb13">
