### ISSUE TITLE
DHI-NVR4108-8P-4KS2 Unable to find cameras

### ISSUE THREAD

**Issue by SgtFoose** [rroller/dahua#455]
Hi all,

Home Assistant question.

I have an NVR DHI-NVR4108-8P-4KS2 on 192.168.178.## in my local network.
The Two cameras are connected PoE on this NVR and have their own subnet 10.1.1.##.
When I add the NVR, I can see an entity NVR Main, NVR Sub, NVR Sub 2 and NVR Sub 3.
When I click on one of these entity's, I see a quick flash of the image and then it goes dark.
Sub 2 and 3 do not work, but think these are disabled in the camera themselves, but this is fine.

How do I add Camera 1 Sub Stream and Camera 2 Sub stream as separate cameras and how do I improve the connection?

I don't seem to have control over which of the two cameras is under NVR MAIN right?

![Image](https://github.com/user-attachments/assets/f81466f9-79c7-43ab-82cf-addce8faad8b)

![Image](https://github.com/user-attachments/assets/0d73a388-5cfa-484b-b982-56b80e4a53a3)

**Comment by arturoparedesq** [comment]
Did you add this on your configuration.yaml archive:
 stream:
  ll_hls: true
  part_duration: 1.0
  segment_duration: 4

**Comment by SgtFoose** [comment]
I did with no success.

Should I also add:

`ffmpeg:`

and

```
camera:
  - platform: mjpeg
    name: Dahua NVR
    mjpeg_url: http://<USERNAME>:<PASSWORD>@<NVR_IP>/cgi-bin/mjpg/video.cgi?channel=1&subtype=1
```
?
