### ISSUE TITLE
Door unlock service/switch for VTO2211G

### ISSUE THREAD

**Issue by luzik** [rroller/dahua#53]
I can't find any switch or service related to unlocking door after adding VTO2211G. How to achieve this ?

**Comment by rroller** [comment]
I need to build this in. I don't currently have a way to test it, which is why I didn't include it yet. I'll add support for this and ask if you can test it for me.

**Comment by luzik** [comment]
i am ready to help

**Comment by rroller** [comment]
0.9.7 is released that adds a service to open doors via a VTO.

## With the UI
<img width="1195" alt="Screen Shot 2021-07-17 at 5 05 23 PM" src="https://user-images.githubusercontent.com/445655/126051940-ec55ddd6-99f8-41ce-bdfd-9344201dfea4.png">

## With YAML
```yaml
service: dahua.vto_open_door
data:
  door_id: 1
target:
  entity_id: camera.cam13_main
```
