### ISSUE TITLE
How can i open door with the VTO2202F?

### ISSUE THREAD

**Issue by TeDeVPrime** [rroller/dahua#69]
Hi guys, plz help me out here.
How can i open the door? i can't find something with Node-Red.

any instructions / examples?

**Comment by rroller** [comment]
Use the service `dahua.vto_open_door` 

## With the UI
<img width="1195" alt="Screen Shot 2021-07-17 at 5 05 23 PM" src="https://user-images.githubusercontent.com/445655/126051940-ec55ddd6-99f8-41ce-bdfd-9344201dfea4.png">

## With YAML
```yaml
service: dahua.vto_open_door
data:
  door_id: 1
target:
  entity_id: camera.cam13_main
```
