### ISSUE TITLE
ability to download recorded videos

### ISSUE THREAD

**Issue by blademckain** [rroller/dahua#97]
**Is your feature request related to a problem? Please describe.**
At the moment there is no home assistant integration that can interact with the dahua camera to view the recorded videos.
It would certainly be innovative to have a quick and easy way to access recorded videos

**Describe the solution you'd like**
Using API
4.11.13 Download Media File between Times
you can download the videos

**Additional context**
a working example here
https://mlog.club/article/3576624

**Comment by rroller** [comment]
Thanks for the example. Do you know of an example Home Assistant integration that allows you to download files? I'm not sure I've seen anything like that before (or to show video clips). One problematic thing is that the native files that Dahua produce are .dav files. DAV is a modified mp4 format and it's not going to play without a conversion. I most likely won't be able to support this but will keep an eye out if I think it can be done easily.

**Comment by GaryOkie** [comment]
Other than my AD410 doorbell, none of my Dahua cameras have an SD-Card as they record only on the NVR.   Unfortunately, I discovered that there is no "NewFile" event raised when a motion event occurs and the video is recorded to the NVR.   This seems to only occur if an SD_Card is installed.

Should there be an additional event handler to subscribe to NVR "channel 0" events, assuming there is such a thing?  How else can NVR-specific events such as the locally-recorded filename be captured that aren't just passed through from the camera?

Maybe the filename can be inferred from the timestamp on the trigger event, but that's iffy.

So if the OP wants to be able to download video from the SD-Card and not the NVR, there is a way forward that should not require any changes to the Dahua integration.

**Comment by GaryOkie** [comment]
More discovery...  the DAV files recorded on the Dahua NVR are from the constant stream of each camera channel.   The recordings are written as individual hour-long DAV files. If you use the NVR Backup to USB drive facility, you will see these hour-long recordings which can be saved as DAV (or MP4 in the newer firmware).

Here is an example of the NVR filepath/name created:
`FilePath=/mnt/dvr/2021-10-04/4/dav/09/0/3/438066/09.00.02-10.00.02[R][0@0][0].dav

You can search the NVR for available files, but it's tricky since it takes 3 separate commands which require a session object id that is temporary...

`<nvr_ip>/cgi-bin/mediaFileFind.cgi?action=factory.create`
returns <object_id>   (valid only for a minute)

`<nvr_ip>/cgi-bin/mediaFileFind.cgi?action=findFile&object=<object_id>&condition.Channel=5&condition.StartTime=2021-10-4%2010:00:00%20&condition.EndTime=2021-10-4%2012:00:00`

`<nvr_ip>/cgi-bin/mediaFileFind.cgi?action=findNextFile&object=<object_id>`

```
items[0].VideoStream=Main
items[0].Channel=4
items[0].Type=dav
items[0].StartTime=2021-10-04 09:00:02
items[0].EndTime=2021-10-04 10:00:02
items[0].Disk=3
items[0].Partition=3
items[0].Cluster=438066
items[0].FilePath=/mnt/dvr/2021-10-04/4/dav/09/0/3/438066/09.00.02-10.00.02[R][0@0][0].dav
items[0].Length=953417728
items[0].Flags[0]=Timing
items[0].CutLength=530432
```

I was not successful using the http RPC_Loadfile command to directly download this file.  It immediately fails with a "file incomplete" error.  Not that I wanted a huge hour long MP4 anyway.

Bottom line - a facility to download recorded videos from the NVR would be very complicated in my view.   On the other hand, accessing them from the camera's SD-Card is much simpler given the specific filename obtained from the "NewFile" event.

**Comment by blademckain** [comment]
Hi guys,
I report the configuration I used to solve this problem (if it were integrated in this component it would be fantastic, but I know it's complicated)

Prerequisite: u have to enable ffmpeg in your configuration.yaml

1. Automation for video download
```
input_text:
  last_recorded_video:
    name: Last Recorded Video
    max: 255
  last_snapshot_camera:
    name: Last SnapShot Camera
    max: 255

shell_command:
  download_recorded_dav: "curl --digest --user {{tvcc_user}}:{{tvcc_pass}} -o /config/www/tmp/last_recorded.dav -g {{tvcc_url}}"
  download_snapshot_camera: "curl --digest --user {{tvcc_user}}:{{tvcc_pass}} -o /config/www/tmp/last_snapshot.jpg -g {{tvcc_url}}"
  convert_recorded_dav: "bash /config/www/tmp/convertdav.sh"

    - alias: "Rilevazione video registrato - Telecamere"
      mode: queued
      variables:
        tvcc_user: !secret tvcc_user
        tvcc_pass: !secret tvcc_pass
      trigger:
         - platform: event
           event_type: dahua_event_received
           event_data:
              Code: NewFile
              action: Pulse
      condition:
        # Only trigger the alarm if it's armed
        condition: or
        conditions:
          - condition: state
            entity_id: alarm_control_panel.alarm
            state: armed_home
          - condition: state
            entity_id: alarm_control_panel.alarm
            state: armed_night
          - condition: state
            entity_id: alarm_control_panel.alarm
            state: armed_away
          - condition: state
            entity_id: alarm_control_panel.alarm
            state: triggered
      action:
        - choose:
            - conditions: "{{ '.dav' in trigger.event.data.data.File }}"
              sequence: 
                - service: input_text.set_value
                  data_template:
                    entity_id: input_text.last_recorded_video
                    value: >
                      {% if trigger.event.data.name == 'TVCC2' %}
                      {% set tvcc_ip = '192.168.x.44' %}
                      {% elif trigger.event.data.name == 'TVCC4' %}
                      {% set tvcc_ip = '192.168.x.42' %}
                      {% elif trigger.event.data.name == 'TVCC5' %}
                      {% set tvcc_ip = '192.168.x.41' %}
                      {% endif %}
                      {{ 'http://'~tvcc_ip~'/cgi-bin/RPC_Loadfile/'~trigger.event.data.data.File }}
                - service: shell_command.download_recorded_dav
                  data_template:
                    tvcc_user: "{{tvcc_user}}"
                    tvcc_pass: "{{tvcc_pass}}"
                    tvcc_url: "{{ states('input_text.last_recorded_video') }}"
                - service: shell_command.convert_recorded_dav
            - conditions: "{{ '.jpg' in trigger.event.data.data.File }}"
              sequence:
                - service: input_text.set_value
                  data_template:
                    entity_id: input_text.last_snapshot_camera
                    value: >
                      {% if trigger.event.data.name == 'TVCC2' %}
                      {% set tvcc_ip = '192.168.x.44' %}
                      {% elif trigger.event.data.name == 'TVCC4' %}
                      {% set tvcc_ip = '192.168.x.42' %}
                      {% elif trigger.event.data.name == 'TVCC5' %}
                      {% set tvcc_ip = '192.168.x.41' %}
                      {% endif %}
                      {{ 'http://'~tvcc_ip~'/cgi-bin/RPC_Loadfile/'~trigger.event.data.data.File }}
                - service: shell_command.download_snapshot_camera
                  data_template:
                    tvcc_user: "{{tvcc_user}}"
                    tvcc_pass: "{{tvcc_pass}}"
                    tvcc_url: "{{ states('input_text.last_snapshot_camera') }}"
          default: []
```

2. Bash script for convert video
```
#!/bin/bash
ffmpeg -y -i /config/www/tmp/last_recorded.dav -c copy -max_muxing_queue_size 9999 /config/www/tmp/last_recorded.mp4 2> /config/www/tmp/last_recorded.log
```
