### ISSUE TITLE
Streaming the camera to a media player uses internal url

### ISSUE THREAD

**Issue by michaelwoods** [rroller/dahua#99]
## Version of the custom_component

0.9.23

## Configuration

```yaml

service: camera.play_stream
data:
  media_player: media_player.bedroom_home_hub
target:
  entity_id:
    - camera.front_door_main

```

## Describe the bug

The stream will fail to play and the logs show that an `internal_url` was used (http://ip_address/...) when I do not have that defined in my configuration. I do have `external_url` only, to avoid this issue with casting devices.

## Debug log

```text
Failed to cast media http://ip_address:8123/api/hls/dd56f293afd20bed8fad30c64b7bde11198bc2d66108f2edc7821a23b354d6b8/master_playlist.m3u8 from internal_url (http://ip_address:8123). Please make sure the URL is: Reachable from the cast device and either a publicly resolvable hostname or an IP address

```

Note that I replaced my real internal address with `ip_address` above.
